---
title: OpenOwnership
timezone: UTC
collections:
  authors:
    title: Authors
    output: false
  guide:
    title: Guide
    output: true
  posts:
    title: Posts
    output: true
  resources:
    title: Resources
    output: false
  team:
    title: Team
    output: false
  uploads:
    title: Uploads
    output: true
  what-we-do:
    title: What We Do
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    image: 
    description: 
    author: 
    layout: post
    permalink: "/news/:title/"
- scope:
    path: ''
    type: pages
  values:
    description: 
    layout: page
- scope:
    path: ''
    type: resources
  values:
    description: 
    file: 
    author: 
    thumbnail-image: 
- scope:
    path: ''
    type: team
  values:
    job-title: 
    image: 
    email: 
    social: 
url: https://www.openownership.org
description: Building an open register of global beneficial ownership in the public
  interest
permalink: pretty
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-paginate-v2
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: http://www.garethjohnsdesign.com
company: OpenOwnership
cookies-text: We use Google Analytics to help us understand website traffic, webpage
  usage and enhance the functionality of our website and improve your user experience.
  We do not capture your personal data or transfer it to anyone else, or use any third-party
  cookies. You can disable the use of cookies from your browser settings. By closing
  this message and continuing to use our website you consent to our use of cookies.
email: info@openownership.org
analytics: UA-88119324-1
logo: "/assets/img/logo.svg"
placeholder: "/assets/img/placeholder.jpgs"
per_page: 12
date_format: "%b %Y"
future: true
social:
  twitter: https://twitter.com/openownership
  medium: https://medium.com/beneficial-ownership
  github: https://github.com/openownership/data-standard
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
pagination:
  enabled: true
  per_page: 6
  limit: 0
  permalink: "/:num/"
  title: ":title — :num of :max"
  sort_field: date
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    slugify:
      mode: raw
      cased: true
    layouts:
    - tags.html
    title: Posts tagged with :tag
    permalink: "/tag/:tag"
imgix:
  source: open-ownership.imgix.net
